Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?useSSL=false
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    database: MYSQL
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        query.in_clause_parameter_padding: true
        format_sql: true
        check_nullability: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace